# Generated by Django 4.1.4 on 2022-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True, verbose_name='fname')),
                ('lname', models.CharField(blank=True, max_length=100, null=True, verbose_name='lname')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),
                ('exp', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='years_of_experience')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='qualification')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='designation')),
                ('services', models.CharField(blank=True, choices=[('Weight Management', 'Weight Management'), ('Sports Nutrition', 'Sports Nutrition'), ('Kids Nutrition', 'Kids Nutrition'), ('Fitness Nutrition', 'Fitness Nutrition')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Dietician',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
