# Generated by Django 4.1.4 on 2022-12-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0002_about_delete_aboutus_delete_contactus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='address2')),
                ('city', models.CharField(blank=True, choices=[('bangalore', 'bangalore'), ('mumbai', 'mumbai'), ('delhi', 'delhi'), ('pune', 'pune')], max_length=100, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='zip')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True, verbose_name='question')),
                ('answer', models.TextField(blank=True, max_length=1024, null=True, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('bangalore', 'bangalore'), ('mumbai', 'mumbai'), ('delhi', 'delhi'), ('pune', 'pune')], max_length=100, null=True, verbose_name='location')),
                ('consulting_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='fee')),
                ('booking_date', models.DateField(blank=True, max_length=100, null=True, verbose_name='date')),
                ('booking_time', models.DateTimeField(blank=True, choices=[('11AM', '11AM'), ('2PM', '2PM'), ('4PM', '4PM'), ('6PM', '6PM')], max_length=100, null=True, verbose_name='time')),
            ],
        ),
    ]
