# Generated by Django 4.1.4 on 2022-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0003_contact_faq_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='consulting_fee',
            field=models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='fee'),
        ),
    ]
