# Generated by Django 4.1.4 on 2022-12-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0005_alter_fee_consulting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='consulting_fee',
            field=models.CharField(blank=True, choices=[('consultion', 'consultion'), ('3Months', '3Months'), ('1Year', '1Year')], max_length=100, null=True, verbose_name='fee'),
        ),
    ]
