# Generated by Django 4.1.4 on 2022-12-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0006_alter_fee_consulting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='booking_time',
            field=models.TimeField(blank=True, choices=[('11AM', '11AM'), ('2PM', '2PM'), ('4PM', '4PM'), ('6PM', '6PM')], max_length=100, null=True, verbose_name='time'),
        ),
    ]
