# Generated by Django 4.1.4 on 2022-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0007_alter_fee_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='booking_time',
            field=models.TimeField(blank=True, choices=[('11:00', '11:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00')], max_length=100, null=True, verbose_name='time'),
        ),
    ]
