# Generated by Django 4.1.4 on 2022-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietician', '0008_alter_fee_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='services',
        ),
    ]
