# Generated by Django 4.1.3 on 2022-12-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('customer_age', models.PositiveIntegerField(default=15, verbose_name='age')),
                ('customer_height', models.FloatField(default=5.0, verbose_name='height')),
                ('food', models.CharField(blank=True, choices=[('vegetarian', 'vegetarian'), ('non-vegetarian', 'non-vegetarian'), ('eggiterian', 'eggiterian')], max_length=50, null=True, verbose_name='food')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True, verbose_name='gender')),
            ],
        ),
    ]
